name: buid images

on:
  push:
    tags:
    - '[0-9].[0-9]+-*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: vars
        run: |
          echo 'tag=${GITHUB_REF#refs/tags/}' >> $GITHUB_ENV
      - name: php74
        if: startsWith(github.ref, 'refs/tags/7.4')
        run: echo "dockerfile=php74/Dockerfile" >> $GITHUB_ENV
      - name: php81
        if: startsWith(github.ref, 'refs/tags/8.1')
        run: echo "dockerfile=php81/Dockerfile" >> $GITHUB_ENV
      - name: Docker build & push
        run: |
          IMAGE=${{ secrets.REGISTRY }}/llaoj/php:${{ env.tag }}
          docker build -f ${{ env.dockerfile }} -t $IMAGE .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}
          docker push $IMAGE
